service: crudapp

plugins:
  - 'serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  region: ap-south-1
  stage: dev
  profile: personal-dev
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: deploys.crudapp-dev
    serverSideEncryption: AES256

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: src/main-lambda.handler
    events:
      - http:
          method: any
          path: /
          cors: true
          private: false
