service:
  name: crudapp

plugins:
  - 'serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  stage: dev
  profile: personal-dev
  runtime: nodejs12.x


functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: src/main-lambda.handler
    events:
      - http:
          method: any
          path: /
          cors: true
          private: false
